const consts = {
    API_URL: process.env.REACT_APP_API_URL,
    OAPI_URL: process.env.REACT_APP_OAPI_URL,

    TOKEN_VALIDATED: 'TOKEN_VALIDATED',
    USER_FETCHED: 'USER_FETCHED',
    BILLING_CYCLES_FETCHED: 'BILLING_CYCLES_FETCHED',
    BILLING_SUMMARY_FETCHED: '',
    TAB_SELECTED: 'TAB_SELECTED',
    TAB_SHOWED: 'TAB_SHOWED',
}

export default consts